### ISSUE TITLE
Updating to QGIS 2.8 breaks area measurements

### ISSUE THREAD

**Issue by sbraden** [sbraden/circle-craters#7]
In QGIS 2.8 the QgsDistanceArea() class does not measure the area of polygons in the user-defined 'area' layer on export. This not only gives incorrect area measurements, but also fails when asked to return only craters that intersect the polygons in the 'area' layer. I'm not 100% sure why these two things are happening in 2.8 when they work in 2.6. It could be two separate issues.

**Comment by inaki-ortizdelandaluce** [comment]
Hi, first of all, thanks a lot for the plugin, it's awesome to have an open source version of this as opposed to ArcGIS counterparts. I have seen a recent update for compatibility with QGIS 2.14 which has been merged to the master branch.  On the other hand, this issue affects 2.8 and has been opened since 2 years ago. Is it still applicable? Which is the highest version of QGIS compatible with the plugin? Any plans to upgrade to QGIS 3 whenever it is rolled out. I would be willing to collaborate on that.
Thanks and congratulations for your work

**Comment by sbraden** [comment]
Hi. Thanks for bringing this to my attention. [The recent update](https://github.com/sbraden/circle-craters/pull/13) changed the function called to measure the area. I need to write official tests to determine if it works as expected. I do plan on upgrading to QGIS 3 when it rolls out. Right now I'll probably keep the version on 2.14 since it was a long-term release and focus on writing those tests. If you want to start a QGIS 3 branch in this project, please feel free to help out! Thanks for your kind words.

**Comment by sbraden** [comment]
Hello. A recently merged pull request updated circlecraters to QGIS 3 ([see #19](https://github.com/sbraden/circle-craters/pull/19)). I'm closing this particular issue for that reason.
